# Generated by Django 4.0.6 on 2022-08-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='generated_icons',
            field=models.ManyToManyField(blank=True, to='generator.favicons'),
        ),
    ]
