# Generated by Django 4.0.6 on 2022-08-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_profile_id_user_alter_profile_generated_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_user',
            field=models.IntegerField(),
        ),
    ]
